# A Docker Compose must always start with the version tag.
version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./data/db/pg:/var/lib/postgresql/data/
  app:
    # depends_on:
    #   - db
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
